[environments.preview.services.luciq-worker]
startCommand = "python -m dramatiq run_agent_background"

[environments.production.services.luciq-worker]
startCommand = "python -m dramatiq run_agent_background" 