MODEL_ACCESS_TIERS = {
    "free": [
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
    ],
    "tier_2_20": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_6_50": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_12_100": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_25_200": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_50_400": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_125_800": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
    "tier_200_1000": [
        "anthropic/claude-sonnet-4-20250514",
        "openrouter/deepseek/deepseek-chat",
        "openrouter/google/gemini-2.5-flash-thinking",
        "openrouter/google/gemini-2.5-pro-preview",
        "openai/gpt-4.1-2025-04-14",
        "openai/gpt-4o-mini",
        "openai/gpt-4o",
    ],
}
